"use client"

import { useEffect, useRef, useState } from "react"
import { useParams, useRouter } from "next/navigation"
import { getMeetingNotes, getMeetingStatus } from "@/lib/api"

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000"

export default function RecapPage() {
  const { id } = useParams<{ id: string }>()
  const router = useRouter()
  const [notes, setNotes] = useState<any>(null)
  const [meeting, setMeeting] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const [videoLoading, setVideoLoading] = useState(false)
  const [videoReady, setVideoReady] = useState(false)
  const pollRef = useRef<ReturnType<typeof setTimeout>>()

  useEffect(() => {
    async function load() {
      try {
        const [m, n] = await Promise.all([getMeetingStatus(id), getMeetingNotes(id)])
        setMeeting(m)
        setNotes(n)
        setLoading(false)
      } catch {
        pollRef.current = setTimeout(load, 3000)
      }
    }
    load()
    return () => clearTimeout(pollRef.current)
  }, [id])

  async function handleGenerateVideo() {
    setVideoLoading(true)
    try {
      await fetch(`${API_BASE}/api/meetings/${id}/recap-video`, { method: "POST" })
      setVideoReady(true)
    } catch {
      alert("Video generation failed.")
    } finally {
      setVideoLoading(false)
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-black text-white flex items-center justify-center">
        <div className="text-center">
          <div className="w-10 h-10 border-2 border-zinc-800 border-t-white rounded-full animate-spin mx-auto mb-5" />
          <p className="text-zinc-300 text-sm font-medium">Einstein is processing your meeting...</p>
          <p className="text-zinc-600 text-xs mt-1.5">Generating notes with Nano Banana · Takes ~15 seconds</p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-black text-white">
      {/* Nav */}
      <nav className="flex items-center justify-between px-8 py-5 border-b border-zinc-900">
        <div className="flex items-center gap-2.5">
          <div className="w-7 h-7 rounded-full bg-white flex items-center justify-center">
            <span className="text-black font-bold text-xs">E</span>
          </div>
          <span className="font-semibold text-sm tracking-tight">Einstein</span>
        </div>
        <button
          onClick={() => router.push("/")}
          className="text-xs text-zinc-600 hover:text-zinc-400 transition"
        >
          ← New meeting
        </button>
      </nav>

      <div className="max-w-2xl mx-auto px-6 py-10">
        {/* Header */}
        <div className="mb-8">
          <p className="text-zinc-600 text-xs font-medium uppercase tracking-widest mb-2">Meeting Recap</p>
          <h1 className="text-2xl font-bold tracking-tight">{meeting?.title}</h1>
          <p className="text-zinc-500 text-sm mt-1">Generated by Einstein · Nano Banana</p>
        </div>

        {notes ? (
          <div className="space-y-4">
            {/* Summary */}
            <section className="bg-zinc-950 border border-zinc-900 rounded-2xl p-5">
              <h2 className="text-xs font-semibold text-zinc-500 uppercase tracking-widest mb-3">Summary</h2>
              <p className="text-zinc-200 text-sm leading-relaxed">{notes.summary}</p>
            </section>

            {/* Key Decisions */}
            {notes.key_decisions?.length > 0 && (
              <section className="bg-zinc-950 border border-zinc-900 rounded-2xl p-5">
                <h2 className="text-xs font-semibold text-zinc-500 uppercase tracking-widest mb-3">Key Decisions</h2>
                <ul className="space-y-2.5">
                  {notes.key_decisions.map((d: string, i: number) => (
                    <li key={i} className="flex items-start gap-3 text-sm text-zinc-200">
                      <span className="w-5 h-5 rounded-full bg-zinc-800 border border-zinc-700 flex items-center justify-center flex-shrink-0 mt-0.5">
                        <span className="text-zinc-400 text-xs">✓</span>
                      </span>
                      {d}
                    </li>
                  ))}
                </ul>
              </section>
            )}

            {/* Action Items */}
            {notes.action_items?.length > 0 && (
              <section className="bg-zinc-950 border border-zinc-900 rounded-2xl p-5">
                <h2 className="text-xs font-semibold text-zinc-500 uppercase tracking-widest mb-3">Action Items</h2>
                <div className="space-y-0">
                  {notes.action_items.map((item: any, i: number) => (
                    <div key={i} className={`flex items-start justify-between gap-4 py-3 ${i < notes.action_items.length - 1 ? "border-b border-zinc-900" : ""}`}>
                      <div className="flex items-start gap-3">
                        <div className="w-4 h-4 border border-zinc-700 rounded mt-0.5 flex-shrink-0" />
                        <p className="text-sm text-zinc-200">{item.task}</p>
                      </div>
                      <div className="text-right flex-shrink-0">
                        <p className="text-xs text-zinc-500 bg-zinc-900 px-2 py-0.5 rounded-full">{item.owner_label}</p>
                        {item.due_date && <p className="text-xs text-zinc-700 mt-1">{item.due_date}</p>}
                      </div>
                    </div>
                  ))}
                </div>
              </section>
            )}

            {/* Next Steps */}
            {notes.next_steps && (
              <section className="bg-zinc-950 border border-zinc-900 rounded-2xl p-5">
                <h2 className="text-xs font-semibold text-zinc-500 uppercase tracking-widest mb-3">Next Steps</h2>
                <p className="text-zinc-200 text-sm leading-relaxed">{notes.next_steps}</p>
              </section>
            )}

            {/* Veo Recap Video */}
            <section className="bg-zinc-950 border border-zinc-900 rounded-2xl p-5">
              <div className="flex items-center justify-between mb-4">
                <div>
                  <h2 className="text-xs font-semibold text-zinc-500 uppercase tracking-widest">Recap Video</h2>
                  <p className="text-zinc-700 text-xs mt-0.5">8-second visual summary powered by Veo 2</p>
                </div>
                <span className="text-xs text-zinc-600 border border-zinc-800 px-2 py-0.5 rounded-full">Veo 2</span>
              </div>

              {videoReady ? (
                <video
                  src={`${API_BASE}/api/meetings/${id}/recap-video`}
                  controls
                  className="w-full rounded-xl"
                />
              ) : (
                <button
                  onClick={handleGenerateVideo}
                  disabled={videoLoading}
                  className="w-full flex items-center justify-center gap-2 bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 text-white text-sm font-medium py-3 rounded-xl transition disabled:opacity-50"
                >
                  {videoLoading ? (
                    <>
                      <span className="w-3.5 h-3.5 border-2 border-zinc-600 border-t-white rounded-full animate-spin" />
                      Generating with Veo 2 (~2 min)...
                    </>
                  ) : "▶ Generate Recap Video"}
                </button>
              )}
            </section>

            {/* Footer */}
            <div className="text-center py-4">
              <p className="text-zinc-700 text-xs">
                AI-assisted · Human-owned · Einstein did not attend, it observed.
              </p>
            </div>
          </div>
        ) : (
          <div className="text-center py-16 bg-zinc-950 border border-zinc-900 rounded-2xl">
            <div className="w-8 h-8 border-2 border-zinc-800 border-t-zinc-400 rounded-full animate-spin mx-auto mb-4" />
            <p className="text-zinc-400 text-sm">Notes are still processing...</p>
            <p className="text-zinc-700 text-xs mt-1">This page will update automatically</p>
          </div>
        )}
      </div>
    </div>
  )
}
